ccxt backtest and ccxt data cache, ccxt backtest example upload, _strategy.py, ccxt.py modified for ccxt backtest
Lumiwealth/lumibot pull request #366
Opened 2024-02-13 16:04 UTC by mrchaos

● ccxt data cache :  lumibot/tools/ccxt_data_store.py
 - This module used duckdb to cache the ccxt data, see the in-source documentation for details.
 - Used when backtesting CCXT.
 
● ccxt data cache test module: tests/test_ccxt_store.py
 
● ccxt backtesting data source : lumibot/data_sources/ccxt_backtesting_data.py
 - This module is similar to the structure of yahoo_data.py.
 - The ccxt data cache module is used here.
 
● ccxt backtesting : lumibot/backtesting/ccxt_backtesting.py
 - This module is similar to the structure of yahoo_backtesting.py.

● ccxt backtesting example : lumibot/example_strategies/ccxt_backtesting_example.py
 - binance, bitmex backtesting example
 - Use `ccxt backtesting data source` as the benchmark data source.

● _strategy.py, ccxt.py  modified for ccxt backtesting

2024-02-14 00:40 UTC, grzesir requested changes
This looks fantastic! Great work!

One small thing: can you add a test for the example strategy? Every example strategy has a test in this file: https://github.com/Lumiwealth/lumibot/blob/dev/tests/backtest/test_example_strategies.py

It should be very straight forward, but it will make sure that future code does not break this backtesting capability (and sometimes helps reveal issues)

2024-02-14 00:48 UTC, grzesir commented on tests/test_ccxt_store.py
> +import duckdb
this should be a dependency in setup.py

2024-02-14 05:55 UTC, mrchaos commented on tests/test_ccxt_store.py
> +import duckdb
I added the dependency to setup.py.

2024-02-14 05:59 UTC, mrchaos commented
Added the example strategy unit test code to the test_example_strategies.py file.

2024-02-14 05:59 UTC, mrchaos commented
> @mrchaos
> 
> This looks fantastic! Great work!
> 
> One small thing: can you add a test for the example strategy? Every example strategy has a test in this file: https://github.com/Lumiwealth/lumibot/blob/dev/tests/backtest/test_example_strategies.py
> 
> It should be very straight forward, but it will make sure that future code does not break this backtesting capability (and sometimes helps reveal issues)

Added the example strategy unit test code to the test_example_strategies.py file.

2024-02-15 04:32 UTC, grzesir commented
> Added the example strategy unit test code to the test_example_strategies.py file.

thank you @mrchaos ! this is a great addition to lumibot, you will now be remembered in history as the one who added this feature.

btw we should probably add this to the docs too, I can do this if you write out a quick overview of how it works.

for now im going to merge this and it will be deployed in our next release (probably over the weekend)

2024-02-15 04:32 UTC, merged

2024-02-15 04:33 UTC, grzesir commented
@mrchaos merged.

please let me know what we should put in the docs for this. if you give me a short writeup (a few sentences with example code) i can add it in

2024-02-19 02:23 UTC, mrchaos commented
> @mrchaos merged.
> 
> please let me know what we should put in the docs for this. if you give me a short writeup (a few sentences with example code) i can add it in

I'll send you the exmaple code and documentation after some more testing.

2024-02-20 01:19 UTC, grzesir commented
Ok perfect, thank you.

Robert Grzesik 347-635-3416


On Sun, Feb 18, 2024 at 9:23 PM Sungho Park ***@***.***>
wrote:

> @mrchaos <https://github.com/mrchaos> merged.
>
> please let me know what we should put in the docs for this. if you give me
> a short writeup (a few sentences with example code) i can add it in
>
> I'll send you the exmaple code and documentation after some more testing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Lumiwealth/lumibot/pull/366#issuecomment-1951584412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIYQK5R66WUO6DMYRFCZELYUKZTHAVCNFSM6AAAAABDGYUQNWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJRGU4DINBRGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>