Theta bidask
Lumiwealth/lumibot pull request #526
Opened 2024-08-15 04:33 UTC by haochili

1. Enabled bid/ask feature with thetadata 
2. Added 36 unit testing feature for thetadata_helper.py
3. Won't show thetadata download on weekends

2024-08-16 22:30 UTC, grzesir requested changes

2024-08-16 22:30 UTC, grzesir commented on lumibot/backtesting/thetadata_backtesting.py
> +            # if asset.asset_type == "option":
clean up comments

2024-08-16 22:30 UTC, grzesir commented on lumibot/tools/thetadata_helper.py
> +        # df.index = df.index.tz_localize("UTC") if df.index.tzinfo is None else df.index
comments cleanup

2024-08-16 22:33 UTC, grzesir approved these changes

2024-08-21 23:01 UTC, haochili commented on lumibot/backtesting/thetadata_backtesting.py
> +            # if asset.asset_type == "option":
I cleaned up the comments

2024-08-21 23:01 UTC, haochili commented on lumibot/tools/thetadata_helper.py
> +        # df.index = df.index.tz_localize("UTC") if df.index.tzinfo is None else df.index
This is cleaned up too

2024-08-21 23:07 UTC, merged